var shops = [
  {
    Structure: "Grand Armor Shop",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: 15,
    "Type?": "",
    "Marketplace Price (approx)": "$1,200.00",
  },
  {
    Structure: "Grand Forge",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: 15,
    "Type?": "",
    "Marketplace Price (approx)": "$1,200.00",
  },
  {
    Structure: "Grand Granary",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: 15,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Grand Stable",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Grand Storehouse",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$1,200.00",
  },
  {
    Structure: "Grand Weapon Shop",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$1,200.00",
  },
  {
    Structure: "Large Barn",
    RN: 3,
    Rarity: "Rare",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 110,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Tavern",
    RN: 3,
    Rarity: "Rare",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 110,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Archery",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Armor Shop",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Bakery",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Forge",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Granary",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Mill",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$1,200.00",
  },
  {
    Structure: "Large Weapon Shop",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Woodshop",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 20,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Stable",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 30,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Large Storehouse",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: 30,
    "Type?": "",
    "Marketplace Price (approx)": "$600.00",
  },
  {
    Structure: "Grand Tavern",
    RN: 3,
    Rarity: "Rare",
    Size: "Majestic",
    Dimensions: "20x20",
    Minted: 75,
    "Type?": "",
    "Marketplace Price (approx)": "$1,200.00",
  },
  {
    Structure: "Majestic Armor Shop",
    RN: 5,
    Rarity: "Legendary",
    Size: "Majestic",
    Dimensions: "20x40",
    Minted: 5,
    "Type?": "",
    "Marketplace Price (approx)": "$12,000.00",
  },
  {
    Structure: "Majestic Forge",
    RN: 5,
    Rarity: "Legendary",
    Size: "Majestic",
    Dimensions: "20x40",
    Minted: 5,
    "Type?": "",
    "Marketplace Price (approx)": "$12,000.00",
  },
  {
    Structure: "Majesting Weapon Shop",
    RN: 5,
    Rarity: "Legendary",
    Size: "Majestic",
    Dimensions: "20x40",
    Minted: 5,
    "Type?": "",
    "Marketplace Price (approx)": "$12,000.00",
  },
  {
    Structure: "Majestic Stable",
    RN: 5,
    Rarity: "Legendary",
    Size: "Majestic",
    Dimensions: "20x40",
    Minted: 10,
    "Type?": "",
    "Marketplace Price (approx)": "$12,000.00",
  },
  {
    Structure: "Tavern",
    RN: 1,
    Rarity: "Common",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 1300,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Barn",
    RN: 1,
    Rarity: "Common",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 1400,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Archery",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Armor Shop",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Bakery",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Granary",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Mill",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Weapon Shop",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Woodshop",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 200,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Forge",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 300,
    "Type?": "",
    "Marketplace Price (approx)": "$60.00",
  },
  {
    Structure: "Stable",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Storehouse",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Hitching Post",
    RN: 1,
    Rarity: "Common",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 1000,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Simple Storehouse",
    RN: 1,
    Rarity: "Common",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 1100,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Archery Stand",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Armor Stand",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Bread Stand",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Grain Stand",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Simple Granary",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Weapon Stand",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Woodworking Stand",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 600,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Simple Forge",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Small",
    Dimensions: "5x5",
    Minted: 800,
    "Type?": "",
    "Marketplace Price (approx)": "$12.00",
  },
  {
    Structure: "Crop",
    RN: 1,
    Rarity: "Common",
    Size: "Farming",
    Dimensions: "5x5",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Animal",
    RN: 1,
    Rarity: "Common",
    Size: "Ranching",
    Dimensions: "5x5",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Grand Temple",
    RN: 4,
    Rarity: "Epic",
    Size: "Grand",
    Dimensions: "20x20",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Majestic Temple",
    RN: 5,
    Rarity: "Legendary",
    Size: "Majestic",
    Dimensions: "20x40",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Temple",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Large Temple",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Potion Stand",
    RN: 1,
    Rarity: "Common",
    Size: "Small",
    Dimensions: "5x5",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Potion Shop",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Large Potion Shop",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Meat Stand",
    RN: 1,
    Rarity: "Common",
    Size: "Small",
    Dimensions: "5x5",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Butchery",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Large Butchery",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Milking Stand",
    RN: 1,
    Rarity: "Common",
    Size: "Small",
    Dimensions: "5x5",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Dairy",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Large Dairy",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Jewelry Stand",
    RN: 1,
    Rarity: "Common",
    Size: "Small",
    Dimensions: "5x5",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Jeweler",
    RN: 2,
    Rarity: "Uncommon",
    Size: "Medium",
    Dimensions: "10x10",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
  {
    Structure: "Large Jeweler",
    RN: 4,
    Rarity: "Epic",
    Size: "Large",
    Dimensions: "10x20",
    Minted: "",
    "Type?": "",
    "Marketplace Price (approx)": "",
  },
];
